### ISSUE TITLE
Patch release of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [tidyverse/ggplot2#4296]
@Hadley @clauswilke @yutannihilation @karawoo @paleolimbot 

A slew of changes in R-devel/macOS has resulted in CRAN requesting a ggplot2 update (one of which is #4293). These updates are rather simple and superficial and the plan is to make a patch release off of the last release branch rather than go through the tedious process of a full release. I'll handle this and the master branch is still open for merging etc.

The patch release will be merged into master once on cran

**Comment by thomasp85** [comment]
It seems everything is fixed on master already, so I'll just cherrypick those commits and do a patch release with these

**Comment by thomasp85** [comment]
This release will fix the vdiffr and all.equal issues reported by CRAN. Further, it will include our transition to the MIT license and a whole bunch of link updating in the docs.

I'll submit today so we can get it out before the cran holidays (hopefully)

**Comment by yutannihilation** [comment]
@thomasp85 
Thanks for handling the release!
Sorry, I forgot I added a tweak that works only on GitHub Actions CI... This is my fault.

https://github.com/tidyverse/ggplot2/blob/0394b9f95bc028f558f4c6fde7c43e744c96bd95/tests/testthat/helper-vdiffr.R#L8-L11

Actually the CRAN check on M1 Mac is still failing.

```
  > test_check("ggplot2")
  Error: vdiffr is not installed
  Backtrace:
       █
    1. └─testthat::test_check("ggplot2")
    2.   └─testthat::test_dir(...)
    3.     └─testthat:::test_files(...)
    4.       └─testthat:::test_files(...)
    5.         └─testthat:::test_files_setup_state(...)
    6.           └─testthat::source_test_helpers(".", env)
    7.             └─testthat::source_dir(path, "^helper.*\\.[rR]$", env = env, wrap = FALSE)
    8.               └─base::lapply(files, source_file, env = env, chdir = chdir, wrap = wrap)
    9.                 └─testthat:::FUN(X[[i]], ...)
   10.                   └─base::eval(exprs, env)
   11.                     └─base::eval(exprs, env)
  Execution halted
```
(https://www.stats.ox.ac.uk/pub/bdr/M1mac/ggplot2.out)

**Comment by thomasp85** [comment]
Goddammit. Let's see what happens. I'll make another patch if they contact me. I hope they can emphasise with the fact that we are shooting a bit in blind with M1 arc

**Comment by thomasp85** [comment]
The first word was not directed at you btw🙂

**Comment by yutannihilation** [comment]
> I hope they can emphasise with the fact that we are shooting a bit in blind with M1 arc

Yeah, I hope so... In case they require another release merely for it, you can just pick #4310. I believe this should work on CRAN.
